name: Build APK with Buildozer

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-11-jdk python3-pip python3-setuptools python3-wheel python3-dev build-essential git ccache libncurses5
        pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyKivyApp-APK
        path: bin/*.apk
